{{- if .Values.sensitiveEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.name" . }}-secrets
  labels:
    {{- include "service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.sensitiveEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
