CREATE DATABASE user_db;
CREATE DATABASE order_db;
CREATE DATABASE payment_db;
CREATE DATABASE ai_db;

GRANT ALL PRIVILEGES ON DATABASE user_db TO icop;
GRANT ALL PRIVILEGES ON DATABASE order_db TO icop;
GRANT ALL PRIVILEGES ON DATABASE payment_db TO icop;
GRANT ALL PRIVILEGES ON DATABASE ai_db TO icop;
